# Generated by Django 5.2.17 on 2026-10-05 15:18

import django.core.validators
import django.db.models.deletion
import mascotas.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=60)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, validators=[mascotas.models.validar_fecha_no_futura], verbose_name='fecha de nacimiento')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'El peso debe ser mayor que 0.')], verbose_name='peso (kg)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='dueño')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('especie__in', ['perro', 'gato', 'otro'])), name='mascota_especie_valida'), models.CheckConstraint(condition=models.Q(('peso_kg__isnull', True), ('peso_kg__gt', 0), _connector='OR'), name='mascota_peso_positivo')],
            },
        ),
    ]
